# Generated by Django 2.2.6 on 2019-11-12 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
