# Generated by Django 2.2.7 on 2019-11-17 14:39

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=imagekit.models.fields.ProcessedImageField(upload_to='movies/images'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
